#!/bin/sh

# Git
find `dirname $0`/bundle -maxdepth 1 -type d \
	-exec test -d {}/.git \; \
	-exec git -C {} pull --verbose \;

# Mercurial
find `dirname $0`/bundle -maxdepth 1 -type d \
	-exec test -d {}/.hg \; \
	-exec hg --cwd {} pull -u \;
